require("plugins.devicons")
require("plugins.dashboard")
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.treesitter")
require("plugins.colorizer")
require("plugins.comment")
require("plugins.autopairs")
require("plugins.autotag")
require("plugins.telescope")
-- require("plugins.nvim-tree")

require("plugins.lsp.lspkind")
require("plugins.lsp.lspsaga")
require("plugins.lsp.mason")
require("plugins.cmp")
require("plugins.null-ls")
